version: '3.1'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - app-network

  nodejs-server:
    container_name: nodejs-server
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    stdin_open: true # docker run -i
    tty: true # docker run -t
    networks:
      - app-network

volumes:
  mongodb-data:
networks:
  app-network:
    driver: bridge
